(()=>{
const style=document.createElement('style');
style.textContent=`.vs-info-btn{display:inline-grid;place-items:center;width:22px;height:22px;margin-left:7px;border:1px solid var(--line);border-radius:50%;background:transparent;color:var(--muted);font:700 13px/1 system-ui;vertical-align:middle;padding:0}.vs-info-backdrop{position:fixed;inset:0;background:#0009;z-index:180;display:none;align-items:flex-end}.vs-info-backdrop.show{display:flex}.vs-info-sheet{width:100%;max-width:760px;margin:0 auto;background:var(--panel);border:1px solid var(--line);border-bottom:0;border-radius:22px 22px 0 0;padding:10px 20px calc(22px + env(safe-area-inset-bottom,0px));box-shadow:0 -12px 45px #0008;max-height:72vh;overflow:auto}.vs-info-grab{width:44px;height:5px;border-radius:5px;background:var(--line);margin:2px auto 15px}.vs-info-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.vs-info-title{font-size:20px;font-weight:800;color:var(--cream)}.vs-info-close{border:0;background:transparent;color:var(--muted);font-size:30px;padding:2px 6px}.vs-info-body{line-height:1.5;margin-top:10px}.vs-info-source{font-size:12px;color:var(--muted);margin-top:14px}`;document.head.appendChild(style);
const layer=document.createElement('div');layer.id='vsInfoLayer';layer.className='vs-info-backdrop';layer.setAttribute('aria-hidden','true');layer.innerHTML='<div class="vs-info-sheet" role="dialog" aria-modal="true"><div class="vs-info-grab"></div><div class="vs-info-head"><div id="vsInfoTitle" class="vs-info-title">Information</div><button id="vsInfoClose" class="vs-info-close" aria-label="Close">×</button></div><div id="vsInfoBody" class="vs-info-body"></div><div id="vsInfoSource" class="vs-info-source"></div></div>';document.body.appendChild(layer);
function close(){layer.classList.remove('show');layer.setAttribute('aria-hidden','true')}
function open(title,body,source=''){document.getElementById('vsInfoTitle').textContent=title;document.getElementById('vsInfoBody').textContent=body;document.getElementById('vsInfoSource').textContent=source;layer.classList.add('show');layer.setAttribute('aria-hidden','false')}
document.getElementById('vsInfoClose').onclick=close;layer.addEventListener('click',e=>{if(e.target===layer)close()});let sy=0;layer.addEventListener('touchstart',e=>{if(e.touches.length===1)sy=e.touches[0].clientY},{passive:true});layer.addEventListener('touchend',e=>{if(sy&&e.changedTouches[0].clientY-sy>80)close();sy=0},{passive:true});window.VerseStudyInfo={open,close};
const INFO={
 precise:['Precise translations','These translations generally stay closer to the wording and structure of the original biblical languages. They can be especially useful when comparing wording during detailed study.'],
 loose:['Loose translations','These translations use more natural or contemporary English and may express the meaning of a phrase less literally. Some choices in this group, such as CSB and NIV, are more balanced than truly loose.'],
 paraphrase:['Paraphrases','Paraphrases prioritize communicating the thought and impact of a passage in natural language rather than closely reproducing its original wording. They are useful for comparison, but should not replace a more precise translation for detailed word study.'],
 word:['Original-language Word Study','This section connects important words in the displayed precise translation with available Hebrew or Greek source information.'],
 common:['Common Commentary','This card uses Matthew Henry Concise as a general Christian commentary source.'],
 sda:['SDA Commentary','This card draws from the Seventh-day Adventist Bible Commentary when a direct note for the selected passage is available.'],
 ai:['AI Commentary','This is an AI-generated study summary intended to reflect a generally middle-ground Seventh-day Adventist perspective. It is not itself a Bible translation or published commentary source.']
};
function addButton(el,key){if(!el||el.querySelector('.vs-info-btn'))return;const d=INFO[key];if(!d)return;const b=document.createElement('button');b.className='vs-info-btn';b.type='button';b.textContent='i';b.setAttribute('aria-label',`About ${d[0]}`);b.onclick=e=>{e.stopPropagation();open(d[0],d[1])};el.appendChild(b)}
function decorate(){document.querySelectorAll('.eyebrow').forEach(el=>{const t=(el.textContent||'').toLowerCase();if(t.startsWith('precise'))addButton(el,'precise');else if(t.startsWith('loose'))addButton(el,'loose');else if(t.startsWith('paraphrase'))addButton(el,'paraphrase')});const pairs=[['wordStudyTitle','word'],['commonCommentaryTitle','common'],['sdaCommentaryTitle','sda']];pairs.forEach(([id,k])=>addButton(document.getElementById(id),k));const ai=document.getElementById('aiCommentary')?.closest('.card')?.querySelector('.eyebrow');if(ai)addButton(ai,'ai')}
decorate();new MutationObserver(decorate).observe(document.body,{subtree:true,childList:true});
for(const el of document.querySelectorAll('div'))if(el.children.length===0&&/V4\.1[4-9]|V4\.20/.test(el.textContent||''))el.textContent=el.textContent.replace(/V4\.1[4-9]|V4\.20/,'V4.17');
})();