(()=>{
const TCW_DB='verseStudy.privateBibles',TCW_STORE='bibles',TCW_KEY='TCW',TCW_FORMAT='verse-study-tcw-v1';
let tcwCache=null,tcwReady=false;
const $=id=>document.getElementById(id);
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(TCW_DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(TCW_STORE))db.createObjectStore(TCW_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbGet(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(TCW_STORE,'readonly'),r=tx.objectStore(TCW_STORE).get(TCW_KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function dbSet(v){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(TCW_STORE,'readwrite');tx.objectStore(TCW_STORE).put(v,TCW_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function dbDelete(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(TCW_STORE,'readwrite');tx.objectStore(TCW_STORE).delete(TCW_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function ensureOption(){if(typeof VERSION_OPTIONS==='undefined')return;const list=VERSION_OPTIONS.paraphrase;if(tcwReady&&!list.some(v=>v.code==='TCW'))list.push({code:'TCW',name:'The Clear Word (private copy)'});if(!tcwReady){const i=list.findIndex(v=>v.code==='TCW');if(i>=0)list.splice(i,1)}}
async function loadTcw(){if(tcwCache)return tcwCache;const stored=await dbGet();if(!stored)return null;let bytes=stored.bytes?new Uint8Array(stored.bytes):null,obj=null;if(bytes){try{if(stored.compressed){const ds=new DecompressionStream('gzip');const ab=await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer();obj=JSON.parse(new TextDecoder().decode(ab))}else obj=JSON.parse(new TextDecoder().decode(bytes))}catch(e){console.warn('TCW load failed',e);return null}}else if(stored.verses)obj=stored;if(!obj||obj.format!==TCW_FORMAT||!obj.verses)return null;tcwCache=obj;return obj}
async function importPackage(file){const bytes=new Uint8Array(await file.arrayBuffer());let obj;if(bytes[0]===0x1f&&bytes[1]===0x8b){const ds=new DecompressionStream('gzip');const ab=await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer();obj=JSON.parse(new TextDecoder().decode(ab))}else obj=JSON.parse(new TextDecoder().decode(bytes));if(!obj||obj.format!==TCW_FORMAT||!obj.verses)throw new Error('That is not a Verse Study Clear Word package.');const n=Object.keys(obj.verses).length;if(n<30000)throw new Error('The package looks incomplete.');await dbSet({compressed:bytes[0]===0x1f&&bytes[1]===0x8b,bytes:bytes.buffer,verseCount:n,importedAt:Date.now()});tcwCache=obj;tcwReady=true;ensureOption();try{syncSettingsUI()}catch{};updatePrivateBibleUI();alert(`The Clear Word is ready (${n.toLocaleString()} verses). You may delete the downloaded .tcw file from your phone.`)}
function addPrivateBibleUI(){const settingsBody=document.querySelector('.settingsbody');if(!settingsBody||$('tcwPrivateSection'))return;const section=document.createElement('section');section.id='tcwPrivateSection';section.className='settings-section';section.innerHTML=`<h2>Private Clear Word</h2><div class="settingsnote">Your copy stays only in this browser's private storage. It is not uploaded to the public Verse Study site.</div><div id="tcwPrivateStatus" class="settingsnote" style="margin-top:10px"></div><input id="tcwFileInput" type="file" accept=".tcw,application/gzip,application/json" style="display:none"><button id="tcwImportBtn" class="resetbtn" type="button">Import my Clear Word copy</button><button id="tcwRemoveBtn" class="resetbtn" type="button" style="display:none;margin-top:8px">Remove Clear Word from this device</button>`;const about=[...settingsBody.querySelectorAll('.settings-section')].find(s=>s.querySelector('h2')?.textContent.trim()==='About Verse Study');if(about)settingsBody.insertBefore(section,about);else settingsBody.appendChild(section);$('tcwImportBtn').onclick=()=>$('tcwFileInput').click();$('tcwFileInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const b=$('tcwImportBtn');b.disabled=true;b.textContent='Importing…';try{await importPackage(f)}catch(err){alert(`Could not import The Clear Word: ${err.message||err}`)}finally{b.disabled=false;b.textContent=tcwReady?'Replace my Clear Word copy':'Import my Clear Word copy';e.target.value=''}};$('tcwRemoveBtn').onclick=async()=>{if(!confirm('Remove The Clear Word from this device?'))return;await dbDelete();tcwCache=null;tcwReady=false;if(settings?.paraphrase==='TCW'){settings.paraphrase='MSG';saveSettings()}ensureOption();syncSettingsUI();updatePrivateBibleUI();render()};updatePrivateBibleUI()}
function updatePrivateBibleUI(){const s=$('tcwPrivateStatus'),ib=$('tcwImportBtn'),rb=$('tcwRemoveBtn');if(!s)return;if(tcwReady){s.textContent='Installed on this device. TCW is available under Paraphrase.';if(ib)ib.textContent='Replace my Clear Word copy';if(rb)rb.style.display='block'}else{s.textContent='Not installed on this device.';if(ib)ib.textContent='Import my Clear Word copy';if(rb)rb.style.display='none'}}
if(typeof publicVerse==='function'){
 const basePublicVerse=publicVerse;
 publicVerse=async function(type,x){if(type!=='TCW')return basePublicVerse(type,x);const data=await loadTcw();if(!data)throw new Error('The Clear Word is not installed on this device. Open Settings → Private Clear Word to import your copy.');const text=data.verses[`${x.book}.${x.chapter}.${x.verse}`];if(!text)throw new Error('Clear Word verse not found');return {text}};
}
function setVersion(){for(const el of document.querySelectorAll('div')){if(el.children.length===0&&el.textContent?.includes('V4.11'))el.textContent=el.textContent.replace('V4.11','V4.12')}}
(async()=>{try{tcwReady=!!(await dbGet())}catch{}ensureOption();addPrivateBibleUI();setVersion();if(tcwReady){try{syncSettingsUI()}catch{};try{const stored=JSON.parse(SAFE_STORAGE.getItem('verseStudy.settings')||'{}');if(stored.paraphrase==='TCW'&&settings.paraphrase!=='TCW'){settings={...settings,paraphrase:'TCW'};syncSettingsUI();render()}}catch{}}})();
})();
