(()=>{
const chapterCache=new Map(),xrefCache=new Map();let runToken=0;
const markerRe=/\[\d+\]|[ⓐ-ⓩ]/g;
const BOOK_IDS=['GEN','EXO','LEV','NUM','DEU','JOS','JDG','RUT','1SA','2SA','1KI','2KI','1CH','2CH','EZR','NEH','EST','JOB','PSA','PRO','ECC','SNG','ISA','JER','LAM','EZK','DAN','HOS','JOL','AMO','OBA','JON','MIC','NAM','HAB','ZEP','HAG','ZEC','MAL','MAT','MRK','LUK','JHN','ACT','ROM','1CO','2CO','GAL','EPH','PHP','COL','1TH','2TH','1TI','2TI','TIT','PHM','HEB','JAS','1PE','2PE','1JN','2JN','3JN','JUD','REV'];
const BOOK_NAMES={GEN:'Genesis',EXO:'Exodus',LEV:'Leviticus',NUM:'Numbers',DEU:'Deuteronomy',JOS:'Joshua',JDG:'Judges',RUT:'Ruth','1SA':'1 Samuel','2SA':'2 Samuel','1KI':'1 Kings','2KI':'2 Kings','1CH':'1 Chronicles','2CH':'2 Chronicles',EZR:'Ezra',NEH:'Nehemiah',EST:'Esther',JOB:'Job',PSA:'Psalms',PRO:'Proverbs',ECC:'Ecclesiastes',SNG:'Song of Solomon',ISA:'Isaiah',JER:'Jeremiah',LAM:'Lamentations',EZK:'Ezekiel',DAN:'Daniel',HOS:'Hosea',JOL:'Joel',AMO:'Amos',OBA:'Obadiah',JON:'Jonah',MIC:'Micah',NAM:'Nahum',HAB:'Habakkuk',ZEP:'Zephaniah',HAG:'Haggai',ZEC:'Zechariah',MAL:'Malachi',MAT:'Matthew',MRK:'Mark',LUK:'Luke',JHN:'John',ACT:'Acts',ROM:'Romans','1CO':'1 Corinthians','2CO':'2 Corinthians',GAL:'Galatians',EPH:'Ephesians',PHP:'Philippians',COL:'Colossians','1TH':'1 Thessalonians','2TH':'2 Thessalonians','1TI':'1 Timothy','2TI':'2 Timothy',TIT:'Titus',PHM:'Philemon',HEB:'Hebrews',JAS:'James','1PE':'1 Peter','2PE':'2 Peter','1JN':'1 John','2JN':'2 John','3JN':'3 John',JUD:'Jude',REV:'Revelation'};
const escHtml=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function htmlToText(html){const box=document.createElement('div');box.innerHTML=String(html||'');return (box.textContent||box.innerText||'').replace(/\s+/g,' ').trim()}
function cleanVerse(text){return String(text||'').replace(/([A-Za-zÀ-ÿ])\d{3,5}\b/g,'$1').replace(markerRe,'').replace(/\s+/g,' ').replace(/\s+([,.;:!?])/g,'$1').trim()}
async function getChapter(type,x){const key=`${type}:${x.book}:${x.chapter}`;if(chapterCache.has(key))return chapterCache.get(key);const p=fetch(`https://bolls.life/get-chapter/${type}/${x.book}/${x.chapter}/`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('chapter '+r.status);return r.json()});chapterCache.set(key,p);try{return await p}catch(e){chapterCache.delete(key);throw e}}
function verseFromChapter(data,verse){if(Array.isArray(data))return data.find(v=>Number(v.verse)===Number(verse))||null;if(Array.isArray(data?.verses))return data.verses.find(v=>Number(v.verse)===Number(verse))||null;return null}
async function getCrossRefs(x){const bid=BOOK_IDS[Number(x.book)-1];if(!bid)return[];const key=`${bid}:${x.chapter}`;if(!xrefCache.has(key)){xrefCache.set(key,fetch(`https://bible.helloao.org/api/d/open-cross-ref/${bid}/${x.chapter}.json`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('xref '+r.status);return r.json()}).catch(()=>null))}const data=await xrefCache.get(key);const row=data?.chapter?.content?.find(v=>Number(v.verse)===Number(x.verse));return Array.isArray(row?.references)?row.references:[]}
function refText(r){const n=BOOK_NAMES[r.book]||r.book;return `${n} ${r.chapter}:${r.verse}${r.endVerse&&r.endVerse!==r.verse?`–${r.endVerse}`:''}`}
function addButtons(el,{note,type,refs}){const row=document.createElement('div');row.className='vs-verse-tools';if(note){const b=document.createElement('button');b.type='button';b.className='vs-verse-tool';b.textContent='† Verse note';b.onclick=e=>{e.stopPropagation();window.VerseStudyInfo?.open('Verse note',note,type)};row.appendChild(b)}if(refs?.length){const b=document.createElement('button');b.type='button';b.className='vs-verse-tool';b.textContent='↗ Cross references';b.onclick=e=>{e.stopPropagation();const body=refs.slice(0,12).map(refText).join('\n');window.VerseStudyInfo?.open('Cross references',body,'OpenBible.info cross references')};row.appendChild(b)}if(row.children.length)el.appendChild(row)}
function renderVerse(el,plain,comment,type,refs){if(!el)return;const text=cleanVerse(plain),note=htmlToText(comment);el.innerHTML=`<div>${escHtml(text)}</div>`;addButtons(el,{note,type,refs})}
const css=document.createElement('style');css.textContent=`.vs-verse-tools{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.vs-verse-tool{border:1px solid var(--line);background:var(--panel2);color:var(--gold);font:700 12px/1 system-ui;padding:7px 9px;border-radius:9px}.vs-verse-tool:active{transform:translateY(1px)}`;document.head.appendChild(css);
if(typeof loadTranslations==='function'){
 loadTranslations=async function(x){const token=++runToken;const slots=[['preciseText',settings.precise],['looseText',settings.loose],['paraphraseText',settings.paraphrase]];const refsPromise=getCrossRefs(x);slots.forEach(async([id,type],idx)=>{const el=document.getElementById(id);try{if(type==='TCW'){const r=await publicVerse(type,x);if(token!==runToken)return;if(el)el.innerHTML=`<div>${escHtml(r.text)}</div>`;if(idx===0){currentPreciseText=r.text;loadWordStudy({...x})}return}const [chapter,refs]=await Promise.all([getChapter(type,x),idx===0?refsPromise:Promise.resolve([])]),item=verseFromChapter(chapter,x.verse);if(!item)throw new Error('verse missing');if(token!==runToken)return;const plain=htmlToText(item.text||'');renderVerse(el,plain,item.comment||'',type,refs);const cleanForStudy=cleanVerse(plain);if(idx===0){currentPreciseText=cleanForStudy;loadWordStudy({...x})}}catch(e){if(token!==runToken)return;try{const r=await publicVerse(type,x);if(token!==runToken)return;if(el)el.innerHTML=`<div>${escHtml(r.text)}</div>`;if(idx===0){currentPreciseText=r.text;loadWordStudy({...x});const refs=await refsPromise;if(token===runToken&&el)addButtons(el,{refs})}}catch{if(el)el.innerHTML=`<div class="small">${escHtml(type)} could not load. Tap the current verse to retry.</div>`}}})}
}
for(const el of document.querySelectorAll('div'))if(el.children.length===0&&/V4\.1[4-9]|V4\.20/.test(el.textContent||''))el.textContent=el.textContent.replace(/V4\.1[4-9]|V4\.20/,'V4.20');
try{render()}catch{}
})();